make dir per test so can run parallel

diff --git a/tests/infra-0 b/tests/infra-0
--- a/tests/infra-0
+++ b/tests/infra-0
@@ -7,7 +7,10 @@
 file1="mymakefile.mk"
 file2="mytestfile"
 tmpfiles="$file1 $file2"
-CLEANUP="rm -rf $tmpfiles"
+STARTDIR="`pwd`"; WORKDIR="$0-OUTPUT"
+CLEANUP="eval (cd $STARTDIR; rm -rf $WORKDIR)"
+$CLEANUP # Zap remnants of any failed run
+mkdir "$WORKDIR"; cd "$WORKDIR"
 
 trap "{ echo 'trapped signal - removing temporary files' ; $CLEANUP ; }" 1 2 3 15
 
@@ -21,7 +24,7 @@ which echo  > /dev/null || { echo "Failure! \"echo\" program missing." ; exit 1;
 echo "Found \"echo\" program."
 
 # Test for dmake program
-${test} -x "${DMAKEPROG}" || { echo "Failure! \"dmake\" is missing." ; exit 1; }
+${test} -x "../${DMAKEPROG}" || { echo "Failure! \"dmake\" is missing." ; exit 1; }
 echo "Found \"dmake\" program."
 
 # Remember to quote variables in generated makefiles( $ -> \$ ).
@@ -32,7 +35,7 @@ ${file2}:
 	touch ${file2}
 EOT
 
-${DMAKEPROG} -r -f $file1
+../${DMAKEPROG} -r -f $file1
 result=$?
 if ${test} ! -e "${file2}"; then
   echo "File missing"
